name: App Building, Testing and Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install python dependencies
        working-directory: flask-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Python backend
        working-directory: flask-backend
        run: python app.py | tee output.log

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: yahoo-buzz-plus

      - name: Run tests
        working-directory: yahoo-buzz-plus
        run: npm run test:headless

      - name: Build Angular app to prod
        if: github.ref == 'refs/heads/main'
        working-directory: yahoo-buzz-plus
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Deploy only if push is to main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: yahoo-buzz-plus/dist/
          branch: prod
          token: ${{ secrets.GH_TOKEN }}
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install python dependencies
        working-directory: flask-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: flask-backend
        run: |
          pytest tests.py
