name: Angular Build and Deploy

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: yahoo-buzz-plus 

      - name: Run tests
        run: npm run test:headless
        working-directory: yahoo-buzz-plus

      - name: Build Angular app to prod
        if: github.ref == 'refs/heads/main'
        working-directory: yahoo-buzz-plus
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Deploy only if push is to main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: yahoo-buzz-plus/dist/
          branch: prod  
          token: ${{ secrets.GH_TOKEN }}
  test backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      working-directory: flask-backend
        # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'

    - name: Install python dependencies
      working-directory: flask-backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run backend tests
      working-directory: flask-backend
      run: |
        python -m unittest discover -s tests