name: Python Flask App CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      working-directory: flask-backend
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or the version you are using

    - name: Install dependencies
      working-directory: flask-backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests
      working-directory: flask-backend
      run: |
        python -m unittest discover -s tests
