name: Python Flask App CI

on:
  push:
    branches:
        - '**'

jobs:
  test backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      working-directory: flask-backend
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or the version you are using

    - name: Install python dependencies
      working-directory: flask-backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run backend tests
      working-directory: flask-backend
      run: |
        python -m unittest discover -s tests
